name: CI CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        # Simulate Build Failure
      - name: Simulate Build Failure
        run: exit 1
        # Build Failure Notification
      - name: Notify Teams on Failure
        if: failure()
        uses: jdcargile/ms-teams-notification@v1.3
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        with:
          message: "Build and Test Failed - ${{ github.repository }} @ ${{ github.run_number }}"
          title: "GitHub Actions Failure"
          themeColor: "ff0000"
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deployment to staging environment successful."
        # Deploy Failure Notication
      - name: Notify Teams on Deployment Failure
        if: failure()
        uses: jdcargile/ms-teams-notification@v1.3
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        with:
          message: "Deployment Failed - ${{ github.repository }} @ ${{ github.run_number }}"
          title: "GitHub Actions Failure"
          themeColor: "ff0000"

